server:
  port: 8097
 
logging:
  level:
    root: debug
  pattern: 
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"
 
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8095/eureka/

management:
  endpoints:
    web:
      exposure:
        include: refresh
      
spring:
  zipkin:
    baseUrl: hhttp://localhost:8098
  sleuth:
    sampler:
      probability: 1      
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
      - id: user
        uri: lb://user
        predicates:
        - Path=/user/**
        filters:
        - RewritePath=/user/(?<path>.*), /$\{path}
      - id: organization
        uri: lb://organization
        predicates:
        - Path=/organization/**
        filters:
        - RewritePath=/organization/(?<path>.*), /$\{path}
