server:
  port: 8097
 
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8095/eureka/

management:
  endpoints:
    web:
      exposure:
        include: refresh
        
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
      - id: user
        uri: lb://user
        predicates:
        - Path=/user/**
        filters:
        - RewritePath=/user/(?.*), /$\{path}
      - id: organization
        uri: lb://organization
        predicates:
        - Path=/organization/**
        filters:
        - RewritePath=/organization/(?.*), /$\{path}
