server:
  port: 8096

logging:
  level:
    root: debug
  pattern: 
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8095/eureka/

management:
  endpoints:
    web:
      exposure:
        include: refresh

spring:
  zipkin:
    baseUrl: hhttp://localhost:8098
  sleuth:
    sampler:
      probability: 1
